language: node_js

node_js:
- '10'

cache:
  directories:
  - node_modules

after_success:
  - bash <(curl -s https://codecov.io/bash)

script:
  - npm run build
  - npm run lint
  - npm run test:coverage
