version: '3'

services:
  api:
    container_name: api
    depends_on:
      - database
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app

  database:
    container_name: database
    image: mysql:5.7
    ports:
      - "33060:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
